config/routes.rb
Rails.application.routes.draw do
  root to:"tasklists#index"
  resources :tasklists
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tasklist.rb
class Tasklist < ApplicationRecord
  validates :content, presence: true, length: { maximum: 10 }
  validates :status, presence: true, length: { maximum: 10 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/tasklists_controller.rb
class TasklistsController < ApplicationController
  before_action :set_tasklist,only:[:show,:edit,:update,:destroy]
  def index
    @tasklist = Tasklist.all.page(params[:page]).per(3)
  end

  def show
  end

  def new
    @tasklist = Tasklist.new
  end

  def create
    @tasklist = Tasklist.new(task_params)
    
    if @tasklist.save
      flash[:success]="タスクが正常に追加されました。"
      redirect_to @tasklist
    else 
      flash.now[:danger]="タスクが追加されませんでした。"
      render :new
    end
  end

  def edit
  end

  def update

    if @tasklist.update(task_params)
      flash[:success] = 'タスクは正常に更新されました'
      redirect_to @tasklist
    else
      flash.now[:danger] = 'タスクは更新されませんでした'
      render :edit
    end

  end

  def destroy
    @tasklist.destroy

    flash[:success] = 'タスクは正常に削除されました'
    redirect_to tasklists_url
  end
end

private
def set_tasklist
  @tasklist = Tasklist.find(params[:id])
end

def task_params
  params.require(:tasklist).permit(:content,:status)
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_flash_tasklists.html.erb
<% flash.each do |task_type, tasks| %>
  <div class="alert alert-<%=task_type %>"><%= tasks%></div>
<% end %>

app/views/layouts/_navbar.html.erb
<header>
  <nav class="navbar navbar-inverse navbar-static-top">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">MessageBoard</a>
      </div>
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to  '新規タスクの追加', new_tasklist_path %></li>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Task</title>
    <%= csrf_meta_tags %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <div class="container">
      <%= render 'layouts/flash_tasklists' %>

      <%= yield %>
    </div>
  </body>
</html>

app/views/tasklists/_form.html.erb
<div class="row">
  <div class="col-xs-12 col-sm-offset-2 col-sm-8 col-md-offset-2 col-md-8 col-lg-offset-3 col-lg-6"></div>
    <%= form_for(task) do |f| %>
      <% if task.errors.any? %>
        <div class="alert alert-warning">
          <ul>
            <% task.errors.full_messages.each do |task| %>
              <li><%= task %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <div class="form-group">
        <%= f.label :content, 'タスク' %>
        <%= f.text_field :content,class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :status, 'ステータス' %>
        <%= f.text_field :status, class: 'form-control' %>
      </div>
      <%= f.submit '追加', class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>

app/views/tasklists/edit.html.erb
<h1>id: <%= @tasklist.id %> のタスク編集ページ</h1>
<%= render "form",task:@tasklist %>

app/views/tasklists/index.html.erb
<h1>タスク一覧</h1>
<% if @tasklist.any? %>

  <table class="table table-striped">
    <thead>
      <tr>
        <th>id</th>
        <th>ステータス</th>
        <th>タスク</th>
      </tr>
    </thead>
    <tbody>
      <% @tasklist.each do |task| %>
        <tr>
          <td><%= link_to task.id,task %></td>
          <td><%= task.content %></td>
          <td><%= task.status %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <div>
  </div>
<% end %>
<%= paginate @tasklist %>

<%= link_to "新規タスクの追加",new_tasklist_path,class: "btn btn-primary" %>

app/views/tasklists/new.html.erb
<h1>タスク新規作成ページ</h1>
<%= render "form",task:@tasklist %>

app/views/tasklists/show.html.erb
<h1>id: <%= @tasklist.id %> のタスク詳細ページ</h1>

<table class="table table-boardered">
  <tr>
    <th>タスク</th>
    <td><%= @tasklist.content %></td>
  </tr>
  <tr>
    <th>ステータス</th>
    <td><%= @tasklist.status %></td>
  </tr>
</table>

<%= link_to"このタスクを編集する",edit_tasklist_path(@tasklist),class: 'btn btn-default' %>
<%= link_to 'このメッセージを削除する', @tasklist, method: :delete, data: { confirm: '本当に削除してよろしいですか？' },class: 'btn btn-danger' %>